# Generated by Django 5.0.6 on 2024-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mriupload',
            name='dicom_file',
        ),
        migrations.AddField(
            model_name='mriupload',
            name='nifti_file',
            field=models.FileField(default='', upload_to='nifti_files/'),
        ),
    ]
