# Generated by Django 5.0.6 on 2024-06-28 11:42

import members.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_mriupload_dicom_file_mriupload_nifti_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mriupload',
            name='nifti_file',
            field=models.FileField(upload_to='nifti_files/', validators=[members.validators.validate_nifti_file]),
        ),
    ]
